(() => {
  'use strict';
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const attr = value => esc(value).replace(/`/g,'&#96;');
  const slugify = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
  const textParagraphs = value => String(value || '').split(/\n\s*\n/).filter(Boolean).map(p => `<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');
  const normalizePath = value => value ? (String(value).startsWith('/') ? String(value) : String(value)) : '';
  const monthNames = ['JAN.','FÉV.','MARS','AVR.','MAI','JUIN','JUIL.','AOÛT','SEP.','OCT.','NOV.','DÉC.'];
  const formatDate = d => { if(!d) return ''; const x=new Date(`${d}T12:00:00`); return Number.isNaN(x.getTime()) ? d : new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(x); };
  const timeLabel = (start,end) => [start,end].filter(Boolean).join(end ? ' — ' : '');
  const scopeClass = s => ({territorial:'scope-territorial',national:'scope-national',europe:'scope-europe',international:'scope-international',multi:'scope-multi'}[s] || 'scope-multi');
  const defaultCover = 'assets/diploval-partage.jpg';
  let publications = [];
  let dynamicActive = null;

  async function getJSON(path, fallback={}) { try { const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(r.status); return await r.json(); } catch(e){ console.warn('Diploval admin content:',path,e); return fallback; } }

  function publicationId(p){ return p.id || slugify(p.title); }
  function renderFeatured(){
    const host=document.querySelector('#admin-featured-publications'); if(!host) return;
    const visible=publications.filter(p=>p.visible!==false);
    const featured=visible.filter(p=>p.featured).slice(0,3); const chosen=(featured.length ? featured : visible.slice(0,3)); if(!chosen.length) return;
    host.innerHTML=chosen.map(p=>{const id=publicationId(p), cover=p.cover||defaultCover; return `<article class="work-card reveal visible"><button aria-label="Ouvrir la fiche ${attr(p.title)}" class="work-open admin-work-open" data-admin-work="${attr(id)}" type="button"><img alt="Image de présentation : ${attr(p.title)}" src="${attr(cover)}"/><span class="work-tag">${esc(p.type||'Publication')}</span><span class="work-scope ${scopeClass(p.scope_filter)}">${esc(p.scope||'Multi-échelles')}</span><span class="work-body"><strong>${esc(p.title)}</strong><small>${esc(p.short_summary||p.summary||'')}</small><span class="work-meta"><span class="work-state">${esc(p.status||'')}</span><span>${esc(p.meta||p.version||p.date_label||'')}</span></span><i aria-hidden="true">→</i></span></button></article>`}).join('');
    const total=document.querySelector('#work-total'), current=document.querySelector('#work-current'), dots=document.querySelector('#work-dots'), prev=document.querySelector('#work-prev'), next=document.querySelector('#work-next');
    const cards=Array.from(host.querySelectorAll('.work-card')); if(total) total.textContent=String(cards.length); if(current) current.textContent='1'; if(dots){dots.innerHTML='';cards.forEach((_,i)=>{const s=document.createElement('span');s.classList.toggle('is-active',i===0);dots.appendChild(s);});}
    let idx=0; const update=()=>{const center=host.scrollLeft+host.clientWidth/2;idx=cards.reduce((best,c,i)=>Math.abs((c.offsetLeft+c.offsetWidth/2)-center)<Math.abs((cards[best].offsetLeft+cards[best].offsetWidth/2)-center)?i:best,0);if(current)current.textContent=String(idx+1);if(dots)Array.from(dots.children).forEach((d,i)=>d.classList.toggle('is-active',i===idx));if(prev)prev.disabled=idx===0;if(next)next.disabled=idx===cards.length-1;};
    if(prev) prev.addEventListener('click',()=>cards[Math.max(0,idx-1)]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})); if(next) next.addEventListener('click',()=>cards[Math.min(cards.length-1,idx+1)]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})); host.addEventListener('scroll',()=>requestAnimationFrame(update),{passive:true}); update();
  }
  function renderLibrary(){
    const host=document.querySelector('#publication-list'); if(!host) return;
    const visible=publications.filter(p=>p.visible!==false);
    host.innerHTML=visible.map(p=>{const id=publicationId(p),cover=p.cover||'';return `<button class="publication-result library-open admin-work-open${cover?' has-cover':''}" data-scope="${attr(p.scope_filter||'multi')}" data-search="${attr([p.keywords,p.title,p.summary,p.details,p.scope,p.type].filter(Boolean).join(' '))}" data-type="${attr(p.type_filter||'note')}" data-admin-work="${attr(id)}" type="button">${cover?`<span class="publication-result-thumb"><img src="${attr(cover)}" alt="" loading="lazy"></span>`:''}<span class="publication-result-copy"><small>${esc(p.type||'Publication')}</small><strong>${esc(p.title)}</strong><em>${esc(p.meta||p.date_label||p.version||'')}</em></span><span class="scope-label ${scopeClass(p.scope_filter)}">${esc(p.scope||'Multi-échelles')}</span><span aria-hidden="true" class="publication-result-arrow">→</span></button>`}).join('')+'<p class="publication-empty" hidden id="publication-empty">Aucun document ne correspond à cette recherche. Essayez un autre mot-clé ou effacez les filtres.</p>';
    setupPublicationFilters();
  }
  function openPublication(id){
    const p=publications.find(x=>publicationId(x)===id); if(!p) return; dynamicActive=p;
    const dialog=document.querySelector('#work-dialog'); if(!dialog) return;
    const q=s=>dialog.querySelector(s); if(q('#dialog-type'))q('#dialog-type').textContent=p.type||'Publication'; if(q('#dialog-title'))q('#dialog-title').textContent=p.title||'';
    if(q('#dialog-body'))q('#dialog-body').innerHTML=(p.cover?`<img class="dialog-admin-cover" src="${attr(p.cover)}" alt="Image de présentation : ${attr(p.title)}">`:'')+`<p class="dialog-summary-lead">${esc(p.summary||p.short_summary||'')}</p>${textParagraphs(p.details)}`;
    if(q('#dialog-meta')) q('#dialog-meta').innerHTML=[p.status,p.version,p.date_label,p.scope?`Échelle : ${p.scope}`:null,p.format].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');
    const pdf=q('#dialog-pdf'); if(pdf){if(p.pdf){pdf.hidden=false;pdf.href=normalizePath(p.pdf);pdf.setAttribute('aria-label',`Consulter le PDF : ${p.title}`)}else{pdf.hidden=true;pdf.removeAttribute('href')}}
    const action=q('#dialog-action'); if(action) action.href=`mailto:contact@diploval.fr?subject=${encodeURIComponent('À propos du document — '+p.title)}`;
    if(typeof dialog.showModal==='function')dialog.showModal(); else dialog.setAttribute('open',''); document.body.classList.add('modal-open');
    try{const u=new URL(location.href);u.searchParams.set('publication',id);u.hash='travaux';history.replaceState({},'',u)}catch{}
    updateDynamicShare(p,id);
  }
  function updateDynamicShare(p,id){const u=new URL(location.href);u.searchParams.set('publication',id);u.hash='travaux';const url=u.toString(),title=`${p.title} — Diploval`,excerpt=(p.summary||p.short_summary||'').slice(0,240);const map={facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,bluesky:`https://bsky.app/intent/compose?text=${encodeURIComponent(title+'\n'+url)}`,linkedin:`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,email:`mailto:?subject=${encodeURIComponent(title)}&body=${encodeURIComponent(excerpt+'\n\n'+url)}`};Object.entries(map).forEach(([k,v])=>{const e=document.querySelector('#share-'+k);if(e)e.href=v});}
  function setupDynamicShare(){const native=document.querySelector('#share-native'),copy=document.querySelector('#share-copy'),status=document.querySelector('#share-status'); if(native)native.addEventListener('click',async e=>{if(!dynamicActive)return;const id=publicationId(dynamicActive);const u=new URL(location.href);u.searchParams.set('publication',id);u.hash='travaux';try{if(navigator.share)await navigator.share({title:dynamicActive.title,text:dynamicActive.summary||'',url:u.toString()});else await navigator.clipboard.writeText(u.toString())}catch{}});if(copy)copy.addEventListener('click',async()=>{if(!dynamicActive)return;const u=new URL(location.href);u.searchParams.set('publication',publicationId(dynamicActive));u.hash='travaux';try{await navigator.clipboard.writeText(u.toString());if(status)status.textContent='Lien de la publication copié.'}catch{if(status)status.textContent=u.toString()}})}
  function setupPublicationFilters(){
    const search=document.querySelector('#publication-search'),type=document.querySelector('#publication-type'),scopes=Array.from(document.querySelectorAll('[data-publication-scope]')),count=document.querySelector('#publication-count'),empty=document.querySelector('#publication-empty'),reset=document.querySelector('#publication-reset'),more=document.querySelector('#publication-load-more'); let scope='all',limit=6; const norm=v=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
    const update=()=>{const items=Array.from(document.querySelectorAll('#publication-list .publication-result'));const q=norm(search?.value),t=type?.value||'all',active=Boolean(q)||t!=='all'||scope!=='all';let matches=0,shown=0,consult=0;items.forEach(item=>{const okq=!q||norm(`${item.dataset.search||''} ${item.textContent}`).includes(q),okt=t==='all'||item.dataset.type===t,oks=scope==='all'||item.dataset.scope===scope,ok=okq&&okt&&oks;if(ok){matches++;const p=publications.find(x=>publicationId(x)===item.dataset.adminWork);if(p?.pdf)consult++;}const show=ok&&(active||matches<=limit);item.hidden=!show;if(show)shown++;});if(count)count.textContent=active?`${matches} travail${matches>1?'aux':''} trouvé${matches>1?'s':''} · ${consult} publication${consult>1?'s':''} consultable${consult>1?'s':''}`:`${matches} travaux référencés · ${consult} publications consultables${shown<matches?` · ${shown} affichés`:''}`;if(empty)empty.hidden=matches!==0;if(more){const rem=Math.max(0,matches-shown);more.hidden=active||rem===0;more.textContent=`Voir ${Math.min(6,rem)} publication${Math.min(6,rem)>1?'s':''} de plus`;}};
    search?.addEventListener('input',update);type?.addEventListener('change',update);scopes.forEach(b=>b.addEventListener('click',()=>{scope=b.dataset.publicationScope;scopes.forEach(x=>{const on=x===b;x.classList.toggle('is-active',on);x.setAttribute('aria-pressed',String(on))});update()}));more?.addEventListener('click',()=>{limit+=6;update()});reset?.addEventListener('click',()=>{if(search)search.value='';if(type)type.value='all';scope='all';limit=6;scopes.forEach(b=>{const on=b.dataset.publicationScope==='all';b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',String(on))});update()});update();
  }
  function renderDossiers(data){const host=document.querySelector('#admin-ongoing-grid');if(!host)return;const list=(data.dossiers||[]).filter(d=>d.visible!==false&&['en_cours','finalisation'].includes(d.status));if(!list.length){host.closest('.ongoing-v206')?.setAttribute('hidden','');return}host.closest('.ongoing-v206')?.removeAttribute('hidden');host.innerHTML=list.slice(0,6).map((d,i)=>`<article class="ongoing-v206__card">${d.cover?`<img class="ongoing-v206__media" src="${attr(d.cover)}" alt="Image de présentation : ${attr(d.title)}" loading="lazy">`:''}<div class="ongoing-v206__cardtop"><span class="ongoing-v206__status"><span aria-hidden="true"></span>${d.status==='finalisation'?'En finalisation':'En cours'}</span><span class="ongoing-v206__scope">${esc(d.scope||'')}</span></div><span class="ongoing-v206__number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><h4>${esc(d.title)}</h4><p>${esc(d.summary||'')}</p><div class="ongoing-v206__foot"><span>${d.status==='finalisation'?'Finalisation en cours':'Instruction en cours'}</span><span>Publication à venir</span></div></article>`).join('')}
  function eventPlace(e){if(e.mode==='online')return ['En ligne',e.platform].filter(Boolean).join(' · ');if(e.mode==='hybrid')return ['Hybride',e.city||e.venue,e.platform].filter(Boolean).join(' · ');return [e.venue,e.city].filter(Boolean).join(' · ')||'Sur place'}
  function registrationButton(e){if(e.access!=='Sur inscription'&&!e.registration)return '';if(e.online_url&&!e.registration)return `<a class="button button-ghost-light agenda-register-button" href="${attr(e.online_url)}" target="_blank" rel="noopener noreferrer">S’inscrire →</a>`;if(e.registration)return `<button class="button button-ghost-light agenda-register-button admin-registration-open" type="button" data-admin-event="${attr(e.title)}">S’inscrire →</button>`;return ''}
  function renderAgenda(data){const host=document.querySelector('#admin-agenda-next'),more=document.querySelector('#admin-agenda-more');if(!host)return;const list=(data.events||[]).filter(e=>e.visible!==false&&e.status!=='termine').sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!list.length){host.hidden=true;if(more)more.hidden=true;return}const e=list[0],d=new Date(`${e.date}T12:00:00`),day=String(d.getDate()).padStart(2,'0'),month=monthNames[d.getMonth()]||'',year=d.getFullYear(),tl=timeLabel(e.start_time,e.end_time),place=eventPlace(e);host.hidden=false;host.setAttribute('aria-label',`Prochain rendez-vous Diploval : ${e.title} le ${formatDate(e.date)}`);host.innerHTML=`<span class="agenda-next-kicker">Prochain rendez-vous</span><div class="agenda-next-date"><strong>${day}</strong><span>${month}<br>${year}</span></div><div class="agenda-next-copy"><small>${esc([formatDate(e.date).split(' ')[0],tl,place].filter(Boolean).join(' · '))}</small><h3>${esc(e.title)}</h3><p>${esc(e.summary||'')}${e.mode!=='online'&&(e.address||e.city)?`<br><strong>${esc([e.venue,e.address,e.city].filter(Boolean).join(' · '))}</strong>`:''}</p>${registrationButton(e)}</div><span class="agenda-next-status">${esc(e.status==='annule'?'Annulé':e.access||'')}</span>`;
    if(more){const rest=list.slice(1);more.hidden=!rest.length;more.innerHTML=rest.length?`<div class="agenda-more-grid">${rest.map(x=>`<article class="agenda-mini"><small>${esc(formatDate(x.date))}${x.start_time?' · '+esc(timeLabel(x.start_time,x.end_time)):''}</small><h3>${esc(x.title)}</h3><p>${esc(eventPlace(x))} · ${esc(x.access||'')}</p><div class="agenda-mini-actions">${registrationButton(x)}</div></article>`).join('')}</div>`:''}
  }
  function openRegistration(e){const dialog=document.querySelector('#registration-dialog');if(!dialog)return;const title=dialog.querySelector('#registration-title'),lead=dialog.querySelector('#registration-event-lead'),field=dialog.querySelector('#registration-event-field');if(title)title.textContent=`S’inscrire — ${e.title}`;const detail=[formatDate(e.date),timeLabel(e.start_time,e.end_time),eventPlace(e)].filter(Boolean).join(' · ');if(lead)lead.innerHTML=`<strong>${esc(detail)}.</strong> Laissez simplement vos coordonnées ; les informations pratiques vous seront adressées avant le rendez-vous.`;if(field)field.value=`${e.title} — ${detail}`;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');document.body.classList.add('modal-open')}
  function setupRegistrationEvents(events){document.addEventListener('click',ev=>{const b=ev.target.closest('.admin-registration-open');if(!b)return;const e=events.find(x=>x.title===b.dataset.adminEvent);if(e)openRegistration(e)})}
  function renderArticles(data){const section=document.querySelector('#actualites'),host=document.querySelector('#admin-articles-list');if(!section||!host)return;const list=(data.articles||[]).filter(a=>a.visible!==false).sort((a,b)=>String(b.date).localeCompare(String(a.date)));section.hidden=!list.length;if(!list.length)return;host.innerHTML=list.map(a=>`<article class="actualite-card">${a.cover?`<img src="${attr(a.cover)}" alt="Image de présentation : ${attr(a.title)}" loading="lazy">`:''}<div class="actualite-card-body"><small>${esc(a.category||formatDate(a.date))}</small><h3>${esc(a.title)}</h3><p>${esc(a.intro||'')}</p>${a.body?`<div class="actualite-body">${textParagraphs(a.body)}</div>`:''}${a.link?`<a href="${attr(a.link)}">${esc(a.link_label||'En savoir plus')} →</a>`:''}</div></article>`).join('')}
  function renderPodcasts(data){const host=document.querySelector('#admin-podcast-episodes');if(!host)return;const list=(data.episodes||[]).filter(e=>e.visible!==false).sort((a,b)=>(Number(b.number)||0)-(Number(a.number)||0));if(!list.length)return;host.innerHTML=list.map(e=>`<article class="podcast-upcoming podcast-admin-episode">${e.cover?`<img src="${attr(e.cover)}" alt="Pochette : ${attr(e.title)}" loading="lazy">`:''}<div class="podcast-episode-number"><span>${esc(e.date?formatDate(e.date):'Épisode')}</span><strong>${String(e.number||'').padStart(2,'0')}</strong></div><div class="podcast-episode-copy"><small>${esc(e.format||'Les Voix du Vivant')}${e.duration?' · '+esc(e.duration):''}</small><h3>${esc(e.title)}</h3><p>${esc(e.summary||'')}</p>${e.audio?`<audio controls preload="metadata" src="${attr(e.audio)}"></audio>`:''}${e.transcript?`<details><summary>Lire la transcription</summary><div>${textParagraphs(e.transcript)}</div></details>`:''}</div></article>`).join('')}
  async function init(){const [pub,dos,agenda,articles,podcasts]=await Promise.all([getJSON('content/publications.json',{publications:[]}),getJSON('content/dossiers.json',{dossiers:[]}),getJSON('content/agenda.json',{events:[]}),getJSON('content/articles.json',{articles:[]}),getJSON('content/podcasts.json',{episodes:[]})]);publications=(pub.publications||[]);renderFeatured();renderLibrary();renderDossiers(dos);renderAgenda(agenda);renderArticles(articles);renderPodcasts(podcasts);setupRegistrationEvents(agenda.events||[]);try{const id=new URL(location.href).searchParams.get('publication');if(id&&publications.some(p=>publicationId(p)===id))setTimeout(()=>openPublication(id),120)}catch{}}
  document.addEventListener('click',e=>{const b=e.target.closest('.admin-work-open');if(b){e.preventDefault();openPublication(b.dataset.adminWork)}});
  setupDynamicShare();
  init();
})();
